/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#002e6a',
        'on-secondary-fixed': '#001a42',
        'surface-container-lowest': '#0e0e11',
        'secondary-fixed': '#d8e2ff',
        'inverse-primary': '#6d3bd7',
        'on-secondary-container': '#e6ecff',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'on-secondary-fixed-variant': '#004395',
        'background': '#131316',
        'error': '#ffb4ab',
        'on-surface-variant': '#cbc3d7',
        'on-error-container': '#ffdad6',
        'secondary': '#adc6ff',
        'surface-bright': '#39393c',
        'primary-fixed': '#e9ddff',
        'on-background': '#e4e1e6',
        'on-primary-fixed': '#23005c',
        'surface': '#131316',
        'surface-dim': '#131316',
        'on-primary-container': '#340080',
        'surface-container-highest': '#353438',
        'error-container': '#93000a',
        'on-surface': '#e4e1e6',
        'on-tertiary-fixed': '#2c1700',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#5516be',
        'outline-variant': '#494454',
        'tertiary-container': '#ca801e',
        'tertiary-fixed': '#ffdcbb',
        'surface-tint': '#d0bcff',
        'on-tertiary-container': '#3f2300',
        'primary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed-variant': '#673d00',
        'on-tertiary': '#482900',
        'tertiary': '#ffb869',
        'secondary-container': '#0566d9',
        'inverse-surface': '#e4e1e6',
        'outline': '#958ea0',
        'primary-container': '#a078ff',
        'primary': '#d0bcff',
        'inverse-on-surface': '#303033',
        'secondary-fixed-dim': '#adc6ff',
        'on-primary': '#3c0091',
        'tertiary-fixed-dim': '#ffb869',
        'surface-variant': '#353438',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Sora', 'sans-serif'],
        label: ['Sora', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
